language: python
python:
 - 3.5
matrix:
  include:
    - env: DJANGO_VERSION="<2.0" TASTYPIE_VERSION="<0.13.3" MONGOENGINE_VERSION="==0.15.3"
      python: 3.5
    - env: DJANGO_VERSION="<2.0" TASTYPIE_VERSION="<0.14.2" MONGOENGINE_VERSION="==0.15.3"
      python: 3.5

services: mongodb
install:
 - pip install "Django$DJANGO_VERSION"
 - pip install "django-tastypie$TASTYPIE_VERSION"
 - pip install "mongoengine$MONGOENGINE_VERSION"
 - python setup.py install
script:
 - python -Wall setup.py test
