language: python
python:
 - 2.7
env:
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.5,<1.6" TASTYPIE_VERSION=">=0.9.12,<0.10.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.5,<1.6" TASTYPIE_VERSION=">=0.10.0,<0.11.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.5,<1.6" TASTYPIE_VERSION=">=0.11.0,<0.12.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.5,<1.6" TASTYPIE_VERSION=">=0.12.0,<0.13.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.5,<1.6" TASTYPIE_VERSION="" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.6,<1.7" TASTYPIE_VERSION=">=0.9.12,<0.10.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.6,<1.7" TASTYPIE_VERSION=">=0.10.0,<0.11.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.6,<1.7" TASTYPIE_VERSION=">=0.11.0,<0.12.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.6,<1.7" TASTYPIE_VERSION=">=0.12.0,<0.13.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == 2*]]; then DJANGO_VERSION=">=1.6,<1.7" TASTYPIE_VERSION="" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == "2.7"]]; then DJANGO_VERSION=">=1.7" TASTYPIE_VERSION=">=0.9.12,<0.10.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == "2.7"]]; DJANGO_VERSION=">=1.7" TASTYPIE_VERSION=">=0.10.0,<0.11.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == "2.7"]]; DJANGO_VERSION=">=1.7" TASTYPIE_VERSION=">=0.11.0,<0.12.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == "2.7"]]; DJANGO_VERSION=">=1.7" TASTYPIE_VERSION=">=0.12.0,<0.13.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
 - if [[$TRAVIS_PYTHON_VERSION == "2.7"]]; DJANGO_VERSION=">=1.7" TASTYPIE_VERSION="" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"; fi
services: mongodb
install:
 - pip install "Django$DJANGO_VERSION"
 - pip install "django-tastypie$TASTYPIE_VERSION"
 - pip install "mongoengine$MONGOENGINE_VERSION"
 - pip install pep8 --use-mirrors
 - pip install pylint --use-mirrors
 - python setup.py install
before_script:
 - pep8 tastypie_mongoengine tests
 - pylint tastypie_mongoengine tests || true
script:
 - python -Wall setup.py test
